const myData = [
  {
    img: "https://res.cloudinary.com/abidazad/image/upload/v1633323815/javascript_qnyfi1.svg",
    name: "JavaScript",
    instructor: "Azad Tamal",
    level: "Beginner",
    rating: 4.7,
    price: 19,
  },
  {
    img: "https://res.cloudinary.com/abidazad/image/upload/v1633323815/c_jinhck.svg",
    name: "C++",
    instructor: "Azad Tamal",
    level: "Expert",
    rating: 4.8,
    price: 29,
  },
  {
    img: "https://res.cloudinary.com/abidazad/image/upload/v1633323815/python_yzfeyo.svg",
    name: "Python",
    instructor: "Azad Tamal",
    level: "Intermediate",
    rating: 4.5,
    price: 12,
  },
  {
    img: "https://res.cloudinary.com/abidazad/image/upload/v1633323815/react_ebz0ny.svg",
    name: "react",
    instructor: "Azad Tamal",
    level: "Beginner",
    rating: 4.4,
    price: 19,
  },
  {
    img: "https://res.cloudinary.com/abidazad/image/upload/v1633323815/nodejs_b4jnu1.svg",
    name: "Node.js",
    instructor: "Azad Tamal",
    level: "Beginner",
    rating: 4.9,
    price: 13,
  },
  {
    img: "https://res.cloudinary.com/abidazad/image/upload/v1633341717/typescript_mz0vld.svg",
    name: "TypeScript",
    instructor: "Azad Tamal",
    level: "Beginner , Intermediate",
    rating: 4.7,
    price: 15,
  },
  {
    img: "https://res.cloudinary.com/abidazad/image/upload/v1633323817/java_ki1ta5.svg",
    name: "Java",
    instructor: "Azad Tamal",
    level: "Intermediate",
    rating: 4.5,
    price: 11,
  },
  {
    img: "https://res.cloudinary.com/abidazad/image/upload/v1633341717/php_hwbpq9.svg",
    name: "PHP",
    instructor: "Azad Tamal",
    level: "Beginner",
    rating: 4.8,
    price: 20,
  },
  {
    img: "https://res.cloudinary.com/abidazad/image/upload/v1633341717/ruby_yhj8t5.svg",
    name: "Ruby",
    instructor: "Azad Tamal",
    level: "Expert",
    rating: 4.7,
    price: 19,
  },
];
export default myData;
