const myData = [
  {
    img: "https://res.cloudinary.com/abidazad/image/upload/v1633323815/javascript_qnyfi1.svg",
    name: "JavaScript",
    instructor: "Azad Tamal",
    project: "Beginner",
    rating: 4.8,
    price: 19,
  },
  {
    img: "https://res.cloudinary.com/abidazad/image/upload/v1633323815/c_jinhck.svg",
    name: "C++",
    instructor: "Azad Tamal",
    project: "Beginner",
    rating: 4.8,
    price: 19,
  },
  {
    img: "https://res.cloudinary.com/abidazad/image/upload/v1633323815/python_yzfeyo.svg",
    name: "Python",
    instructor: "Azad Tamal",
    project: "Beginner",
    rating: 4.8,
    price: 19,
  },
  {
    img: "https://res.cloudinary.com/abidazad/image/upload/v1633323815/react_ebz0ny.svg",
    name: "react",
    instructor: "Azad Tamal",
    project: "Beginner",
    rating: 4.8,
    price: 19,
  },
  {
    img: "https://res.cloudinary.com/abidazad/image/upload/v1633323815/nodejs_b4jnu1.svg",
    name: "Node.js",
    instructor: "Azad Tamal",
    project: "Beginner",
    rating: 4.8,
    price: 19,
  },
  {
    img: "",
    name: "Django",
    instructor: "Azad Tamal",
    project: "Beginner",
    rating: 4.8,
    price: 19,
  },
  {
    img: "",
    name: "Java",
    instructor: "Azad Tamal",
    project: "Beginner",
    rating: 4.8,
    price: 19,
  },
  {
    img: "",
    name: "C#",
    instructor: "Azad Tamal",
    project: "Beginner",
    rating: 4.8,
    price: 19,
  },
  {
    img: "",
    name: "Go",
    instructor: "Azad Tamal",
    project: "Beginner",
    rating: 4.8,
    price: 19,
  },
];
export default myData;
